"""initial schema — projects, decisions (versioned), graph_edges, document_chunks (pgvector)

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-23

Metadata-driven initial migration: enables pgvector and creates all ORM tables from Base.metadata. This
avoids autogenerate's handling of the pgvector column type and is a valid, reversible first revision.
Subsequent revisions can be autogenerated.
"""
from __future__ import annotations

from alembic import op

from edos.db import models  # noqa: F401 — registers tables on Base.metadata
from edos.db.base import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
